version: '3'
services:
    mysql57:
        image: mysql:5.7
        restart: unless-stopped
        container_name: mysql57-container
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: blog_posts
            MYSQL_USER: tuan
            MYSQL_PASSWORD: 123456
        volumes:
          - /var/lib/mysql57-data:/var/lib/mysql

    db:
      container_name: mysql8
      build:
        context: .
        dockerfile: Dockerfile.db
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: blog_posts
        MYSQL_USER: tuan
        MYSQL_PASSWORD: 123456
      ports:
        - '3305:3306'

    backend:
      restart: always
      container_name: backend
      depends_on:
        - db
      build:
        context: ./server
        dockerfile: Dockerfile
      ports:
        - '3002:3002'

    frontend:
      container_name: frontend
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - '3000:3000'





