version: '3'
services:
    mysql57:
        image: mysql:5.7
        restart: unless-stopped
        container_name: mysql57-container
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DB: blog_posts
            MYSQL_USER: lehungtran12
            MYSQL_PASSWORD: 123456
        volumes:
            - /var/lib/mysql57-data:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    db:
      container_name: mysql8
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DB: blog_posts
        MYSQL_USER: lehungtran12
        MYSQL_PASSWORD: 123456
      ports:
        - '3305:3306'
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    frontend:
        container_name: frontend_compose
        build:
          context: ./frontend
          dockerfile: Dockerfile
        ports: 
          - '3000:3000'
    backend:
        restart: always
        container_name: backend_compose
        build:
          context: ./server
          dockerfile: Dockerfile
        ports: 
          - '3002:3002'